// The corresponding .js file is generated by an esbuild plugin, which takes the
// wasm code from the npm package - it doesn't come separated from the Web Audio
// integration, which I don't want.

// https://github.com/Signalsmith-Audio/signalsmith-stretch/blob/2133f41a8f2766d2ade2e665fcf04f9ff7fd74a7/web/emscripten/main.cpp
export interface SignalsmithStretchModule {
    HEAP8: Uint8Array;

    // This must be called right after initializing the wasm module.
    _main: () => void;

    _setBuffers: (channels: number, length: number) => number;
    _blockSamples: () => number;
    _intervalSamples: () => number;
    _inputLatency: () => number;
    _outputLatency: () => number;
    _reset: () => void;
    _presetDefault: (nChannels: number, sampleRate: number) => void;
    _presetCheaper: (nChannels: number, sampleRate: number) => void;
    _configure: (
        nChannels: number,
        blockSamples: number,
        intervalSamples: number,
        splitComputation: boolean,
    ) => void;
    _setTransposeFactor: (multiplier: number, tonalityLimit: number) => void;
    _setTransposeSemitones: (semitones: number, tonalityLimit: number) => void;
    _setFormantFactor: (multiplier: number, compensate: boolean) => void;
    _setFormantSemitones: (semitones: number, compensate: boolean) => void;
    _setFormantBase: (freq: number) => void;
    _seek: (inputSamples: number, playbackRate: number) => void;
    _process: (inputSamples: number, outputSamples: number) => void;
    _flush: (outputSamples: number) => void;
}

var SignalsmithStretch: () => Promise<SignalsmithStretchModule>;

export var SignalsmithStretch: () => Promise<SignalsmithStretchModule>;
